# Generated by Django 4.2.6 on 2024-04-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0003_alter_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rule',
            name='condition',
        ),
        migrations.AddField(
            model_name='rule',
            name='operator',
            field=models.CharField(choices=[('==', 'equals'), ('>', 'greater than'), ('<', 'less than')], default='==', help_text='Comparison operator', max_length=2),
        ),
        migrations.AddField(
            model_name='rule',
            name='subject',
            field=models.CharField(default='temperature', help_text="The subject to check, e.g., 'temperature'", max_length=100),
        ),
        migrations.AddField(
            model_name='rule',
            name='value',
            field=models.CharField(default='25', help_text="Value to compare the subject against, e.g., '25'", max_length=50),
        ),
        migrations.AlterField(
            model_name='rule',
            name='action',
            field=models.CharField(help_text="Action to perform, e.g., 'turn_on: heater'", max_length=255),
        ),
    ]
